fix translating from selection

diff --git a/translate b/translate
--- a/translate
+++ b/translate
@@ -1,100 +1,191 @@
-#!/bin/bash
+#!/usr/bin/env bash
 ##########################################
 # Date: 04/21/2020
-# Author: belkadev
-# Description: google translation cli tool
-# Usage: $0 [source] [target] [text]
-# more details at https://github.com/BelkaDev/GoogleTts/
-# what's missing? Definitions and synonyms in source language
-# Requires:  jq, xclip (optional)
+# Author: belkadev <https://github.com/belkadev/>
+# Description: A google text-to-speech cli script
+# Disclaimer: Please keep in mind this is unofficial,
+# and it's recommended  to support the official "Google TTS" project.
+# Usage: $0 [--lang | -l <language code> ] <text>
+# Requires:  xclip (optional)
+# Todo: ignore urls and other irrelevant characters
 ##########################################
-########Default config##########
+########Default settings##########
 ##############################
-#######
-source_language="auto"
-target_language="en-us"
-##############################
-################################
-urlencode() {
-trim=$(echo "$1" | tr -s " " | tr -d '011\012\015' )
-res="${trim// /"%20"}"
-echo $res
+####### $0 --help for more details
+cachedir=$HOME/.cache/speech
+mediaplayer=mpv
+lang="en-us"
+auto=false
+translate=false; to=$lang
+keep=false
+usepatterns=false
+##### patterns (ignore/replace words) ####
+patterns='{
+"https://";"",
+"http://";"",
+"www.";"",
+"\";"",
+"btw";"by the way",
+}'
+#############################
+###############################
+function print_help() {
+	  echo ""
+	  echo ""
+	  echo "Usage:"
+	  echo "  $(basename $0) [options] [text]"
+	  echo "  If no text is provided, current selection will be processed (requires an x env)"
+	  echo "  All default settings can be changed at the top of the script "
+	  echo "  Executing twice will stop the ongoing playback "
+	  echo "  Argument stack importance order: language > auto > translate"
+	  echo "  The higher will always dismiss the others. "
+	  echo "  https://github.com/BelkaDev/GoogleTts for more details."
+	  echo ""
+	  echo "Options:"
+	  echo "   -l, --lang <lang>	    Specify the speech language; must be a valid Google tag
+	  		    [default:$lang]"
+	  echo ""
+
+	echo "   -a, --auto 		    Auto detect language and read.
+	  		    [default:$auto]" 
+	  echo ""
+
+	echo "   -t, --translate [lang]   Text is translated before being read;If no target 
+			    language is given, translate to default language
+	      		    [default:$translate,$lang]"  
+	  echo ""
+	echo "   -k, --keep   	    Store audio file in the default cache directory
+	      		    [default:$keep]"  
+	  echo ""
+	  echo "   -p, --pattern 	    Allow filters.They can be changed in the script file
+	  		    [default:$usepatterns]" 
+	  echo ""
+
+	echo "   -c, --clear-cache 	    Remove all the cached audio files and exit" 
+	echo "   -v, --verbose 	    show output details" 
+	echo "   -h, --help 		    Print this menu and exit" 
 }
-while [ "$#" -gt 1 ]; do
+urlencode() {
+    old_lc_collate=$LC_COLLATE
+    LC_COLLATE=C
+    local length="${#1}"
+    for (( i = 0; i < length; i++ )); do
+        local c="${1:i:1}"
+        case $c in
+             [#\[\]\ ]) printf '%%%02X' "'$c" ;;
+            *) printf "$c" ;;
+        esac
+    done
+    LC_COLLATE=$old_lc_collate
+}
+
+replace() {
+out="$1"
+words="$(echo "${patterns:1:-1}" | cut -f1 -d ";")"
+words=(${words/// })
+alt="$(echo "${patterns:1:-1}" | cut -f2 -d ";")"
+IFS=',';alt=(${alt}); unset IFS;
+for (( i = 0; i < ${#words[@]} ; i++ )); do
+if [[ "$out" == *"${words[$i]:1:-1}"* ]]; then
+[[ $verboseflag == true ]] && echo "replaced ${words[$i]:1:-1} with "${alt[$i]}""> /dev/tty
+
+out="${out/${words[$i]:1:-1}/${alt[$i]:1:-1}}" 	
+fi
+done
+echo $out
+}
+#######Send kill signal#########
+###Small workaround to kill the mediaplayer when the script is running 
+pid=$(pgrep -f ${mediaplayer} | grep -v $$)
+pscript=$(pgrep -f ${BASH_SOURCE[0]} | grep -v $$)
+if (( ${#pid} > 0 )) && (( ${#pscript} > 0 )); then
+kill -9 $(pgrep -f ${BASH_SOURCE[0]} | grep -v $$) &>/dev/null
+kill -9 $(pgrep -f $mediaplayer | grep -v $$) ;exit 0;fi
+#######Parse arguments#########
+ [ "$#" -ne 0 ] && query=$(echo "${@: -1}");
+ langflag=false
+while [ "$#" -gt 0 ]; do
   case "$1" in
-    from) source_language="$2";shift;;
-    to) target_language="$2";shift;;
-    *)  echo "couldn't parse parameters" && exit 1
+    -l|--lang) langflag=true;lang="$2";shift 1; [ "$#" -eq 1 ] && query="$(echo "$(xclip -o)" |  awk '$1=$1')"  ;;
+    -a|--auto) auto=true;;
+    -t|--translate) translate=true && query="$(echo "$(xclip -o)" |  awk '$1=$1')" 
+     if [ "$2" != "$query" ];then to="$2"; shift 2
+	else to="$lang";shift;fi ;;	
+    -h|--help) print_help && exit 0;;
+    -c|--clear-cache)  read -p "removing all files in $cachedir, confirm? [Y/n] " yn;;
+   -v|--verbose) verboseflag=true;;
+    -p|--pattern) usepatterns=true;;
+    -*) echo "unknown option: $1
+$(basename $0) --help for more details." >&2; exit 1;;
+    *)  query=$(echo "${1}");;
   esac
   shift
 done
-if [ -n "$1" ]; then
-query="$1"
-else
-query="$(echo "$(xclip -o)")"
+case "$query" in
+    -t|-a|-l|--translate|--auto|--lang) query="$(echo "$(xclip -o)" |  awk '$1=$1')";;
+
+    -h|--help) print_help && exit 0;;
+    -c|--clear-cache)  read -p "removing all files in $cachedir, confirm? [Y/n] " yn;
+ case $yn in
+        [Y]) rm $cachedir/*; echo "cleared cache";;
+    esac
+    exit 0;;
+   -v|--verbose) verboseflag=true;;
+    -p|--pattern) usepatterns=true;;
+    -*) echo "unknown option: $1
+$(basename $0) --help for more details." >&2; exit 1;;
+esac
+#############################
+#######Process input#########
+if [[ $translate == true && $auto == false && $langflag == false ]]; then
+	[[ $verboseflag == true ]] && echo "translating text to $to"
+	data=$(gtranslate to $to "$query")
+	query=$(echo "$data" | grep -w "translation" | cut -f2 -d ":")
+	lang=$(echo "$data"  | grep -w "target_lang" | cut -f2 -d ":")
+	[[ $verboseflag == true ]] && echo "translated text: $query"
 fi
-encoded=$(urlencode "$query")
-response=$(curl --data-urlencode "q=$encoded" -sA "ff" https://translate.google.com/translate_a/single\?client\=webapp\&sl\=$source_language\&tl\=$target_language\&hl\=$target_language\&dt\=at\&dt\=bd\&dt\=ex\&dt\=ld\&dt\=md\&dt\=qca\&dt\=rw\&dt\=rm\&dt\=sos\&dt\=ss\&dt\=t\&dt\=gt\&source\=bh\&ssel\=0\&tsel\=0\&xid\=1791807%2C45625687%22C45626150\&kc\=1\&tk)
 
-
-length=$(echo "$response" | jq '.[0]' | jq length)
-if (( length > 2 )); then
-for (( i = 0; i < $length; i++ )); do
-add=$(echo $response | jq '.[0]' | jq --argjson i "$i" '.[$i]' | jq '.[0]' | awk  '{gsub("\\\\n","\n")};1')
-translation=$(echo $translation ${add:1:-1})
+if [[ $auto == true ]]; then lang="$(gtranslate "$query" | grep -w "source_lang" | cut -f2 -d ":")";if [[ $verboseflag == true ]]; then echo "Language detected: $lang";fi;fi
+[ -z "$query" ] && query="$(echo "$(xclip -o)" |  awk '$1=$1')"
+[[ $verboseflag == true ]] && echo "reading (($query)) in $lang"
+qlen="${#query}"
+[ $qlen -le 0 ] && echo "error parsing arguments. exiting" && exit 1;
+query=$(echo "$query"  | tr '\n' ' ')
+#######Split text#######
+maxlen=198
+if (( qlen > $maxlen )); then
+declare -a paragraphs
+length=$qlen
+index=0
+pointer=0
+while [[ $length -gt 0 ]]; do
+paragraphs[$index]=${query:$pointer:$maxlen}
+(( pointer+=$maxlen ))
+(( length-= $maxlen ))
+(( index++ ))
 done
-else 
-translation=$(echo "$response" | jq '.[0]' | jq '.[0]' |  jq '.[0]')
+else paragraphs[0]="$query"; fi
+################################
+# avoid lengthy filenames (deprecated)
+#len="${#urlq}"
+#if (( len > 50 )); then
+#filename="longtext"
+#removeflag=1
+#fi#############################
+#######Get the response############
+for p in "${paragraphs[@]}"; do
+[[ $usepatterns == true ]] &&  p=$(replace "$p")
+encoded=$(urlencode "$p")
+filename=$(echo $lang$encoded | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]' )
+if ! [ -f "$cachedir/$filename.ogg" ]; then
+$(curl -sA "Firefox" "https://translate.google.com/translate_tts?ie=UTF-8&q=%22${encoded}%22&tl="$lang"&client=tw-ob" -o $cachedir/$filename.ogg)
 fi
-# update this
-#
-
-lang=$(echo "$response"  | jq -c '.[2]' )
-echo "source_lang:${lang:1:-1}"
-echo ""
-echo "target_lang:${target_language}"
-echo ""
-echo "source_text:${query}"
-echo ""
-echo "translation:$translation"
-echo ""
-
-
-check=$(echo "$response"  | jq '.[1]' | jq length)
-if (( $check > 0 )); then
-ntranslation_type=$(echo "$response" | jq '.[1]' |  jq '.[]' | jq '.[0]' | wc -l) 
-echo "TRANSLATIONS:"
-echo "-------------"
-for (( j = 0; j < $ntranslation_type; j++ )); do
-(( tempj = j + 1 ))
-translation_type=$(echo "$response" | jq '.[1]' | jq '.[]' | jq '.[0]' | head -$tempj | tail -1 )
-# expressions -------------------------------noun
-ntranslations=$(echo "$response" | jq '.[1]' | jq --argjson j "$j" '.[$j]' | jq '.[1]' | jq length) # noun only
-echo "	${translation_type:1:-1}: $ntranslations"
-for (( i = 0; i < $ntranslations; i++ )); do
-test=$(echo "$response" | jq '.[1]' | jq --argjson j "$j" '.[$j]' | jq '.[2]' | jq --argjson i "$i" '.[$i]' | jq '.[1]' )
-
-translations=$(echo "$response" | jq '.[1]' | jq --argjson j "$j" '.[$j]' | jq '.[1]' | jq --argjson i "$i" '.[$i]')
-# loop over each translation 
-#########################
-#########################
-
-parsed=$(echo "$translations" | sed 's/<[^>]*>//g')
-output=$(printf $translation:"\n${test:0}")
-test=$(echo $test | sed 's/"//g' | tr -s " ")
-echo "	$i: ${translations:1:-1}: (${test:2:-2})"
-done
-done
+################################
+############read the output
+$mediaplayer "$cachedir/$filename.ogg" &>/dev/null;
+if  [ -f "$cachedir/$filename.ongoing" ]; then
+[[ $keep == false ]] && rm $cachedir/$filename.ogg;
 fi
-nexamples=$(echo "$response" | jq '.[13]' | jq '.[0]' | jq length )
-if (( $nexamples > 0 )); then
-echo ""
-echo "EXAMPLES:"
-echo "---------"
-# expressions 
-for (( i = 0; i < $nexamples; i++ )); do
-example=$(echo "$response" | jq '.[13]' | jq '.[0]'  | jq  --argjson i "$i" '.[$i]' | jq '.[0]' )
-parsed=$(echo "$example" | sed 's/<[^>]*>//g')
-echo "	$i: ${parsed:1:-1}"
 done
-fi
+exit 0 
+#EOF
